server:
  port: 8101
spring:
  application:
    name: cloud-eureka-service
eureka:
  instance:
    hostname: localhost.eureka8101.com
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8101/eureka/
#      defaultZone: http://${eureka.instance.hostname}:8102/eureka/