server:
  port: 3344

spring:
  application:
    name: cloud-config-service
  cloud:
    bus:
      refresh:
        enabled: true
    config:
      server:
        git:
          search-paths:
            - springcloudconfig
          uri: https://gitee.com/zhuhaiong/springcloudconfig.git
      label: master
  kafka:
    bootstrap-servers: localhost.kafka:9092
    consumer:
      group-id: springcloudConfig
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost.eureka8101.com:8101/eureka/
#      defaultZone: http://localhost.eureka8101.com:8101/eureka/,http://localhost.eureka8101.com:8102/eureka/