server:
  port: 83
spring:
  application:
    name: nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost.kafka:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
zhl:
  config:
    pay:
      serverpath: http://nacos-pay-server/
      orderpath: /nacos/pay/order