server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: CLOUD-PAYMANAGER-HYSTRIX-SERVICE
#          uri: http://localhost:8085
          uri: lb://CLOUD-PAYMANAGER-HYSTRIX-SERVICE
          predicates:
            - Path=/payment/**

        - id: CLOUD-PAYMANAGER-SERVICE
          uri: lb://CLOUD-PAYMANAGER-SERVICE
          predicates:
            - Path=/payment/**
      discovery:
        locator:
          enabled: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost.eureka8101.com:8101/eureka/
#      defaultZone: http://localhost.eureka8101.com:8101/eureka/,http://localhost.eureka8101.com:8102/eureka/