server:
  port: 8090
spring:
  application:
    name: nacos-pay-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost.kafka:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'