server:
  port: 80
spring:
  application:
    name: cloud-consumer-service
eureka:
  #  instanc中的配置是让该服务使用IP注册到注册中心，而不是hostname
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost.eureka8101.com:8101/eureka/,http://localhost.eureka8101.com:8102/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.zhl.feignconsumer.service: debug